name: VPS con Guardado y Apagado Seguro (CORREGIDO)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 330
    steps:
      - name: "1. Descargar el contenido del repositorio"
        uses: actions/checkout@v4

      - name: "2. Instalar Tailscale y CONFIGURAR USUARIO"
        run: |
          # Instalar Tailscale
          curl -fsSL https://tailscale.com/install.sh | sh
          
          # ### CORRECCIÓN 1: ESTABLECER LA PUTA CONTRASEÑA ###
          # Esto le pone la contraseña 'runnerpass' al usuario 'runner'
          echo "runner:runnerpass" | sudo chpasswd
          
          # ### CORRECCIÓN 2: QUITAR LA BARRA VERDE DE TMATE ###
          echo "set -g status off" >> /home/runner/.tmate.conf

      - name: "3. Conectar a Tailscale y mostrar datos"
        run: |
          # Conectar a tu red de Tailscale
          sudo tailscale up --authkey=tskey-auth-kFSozaELnc11CNTRL-AYAfNFLubL893hLZMQsZL81HVDEZuCAx --hostname=github-vps
          
          echo "--------------------------------------------------------------------"
          echo "CONEXIÓN POR TAILSCALE (SSH):"
          echo "ssh runner@$(tailscale ip -4)"
          echo "CONTRASEÑA: runnerpass"
          echo "--------------------------------------------------------------------"

      - name: "4. Iniciar Tmate (CORREGIDO)"
        # Esta acción ya viene configurada para no pedir claves con el "limit-access-to-actor: false"
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      - name: "5. PASO FINAL: Guardar todo antes de apagar"
        if: always()
        run: |
          echo "Límite de tiempo alcanzado o sesión desconectada. Iniciando guardado..."
          git config --global user.name 'GitHub Actions VPS'
          git config --global user.email 'actions@github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No se encontraron cambios para guardar."
          else
            echo "Cambios detectados. Guardando en el repositorio..."
            git commit -m "Guardado automático de la sesión de la VPS"
            git push
            echo "¡Trabajo guardado con éxito! La VPS se apagará ahora."
          fi
